name: Hello World

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Name to greet'
        required: false
        default: 'World'

  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

          echo "jq: $(jq --version)"
          echo "curl: $(curl --version)"

      - name: Show System Information
        run: |
          echo "Running on $(uname -s) $(uname -r)"
          echo "Current user: $(whoami)"
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"
      - name: Run a one-line script
        run: echo Hello ${{ inputs.username }}
      - name: Show current date
        run: date
  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display files in the repository
        run: ls -la