name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List files changed since last commit
        run: |
          echo "📂 Files changed since last commit:"
          git diff --name-only HEAD~1 HEAD || echo "No diff found"
