name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Confirmation
        run: echo "🚀 Deploy triggered because Build finished successfully!"
