on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Confirmation
        run: echo "✅ Build succeeded, now running deploy!"
