name: Hello World

env:
  USERNAME: "aa-nadim"

on:
  workflow_dispatch:
    inputs:
        username: 
          description: 'Name to greet'
          required: false
          default: 'World'

  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Show System Information
        run: |
          echo "Running on $(uname -s) $(uname -r)"
          echo "Current user: $(whoami)"
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"

      - name: Run a one-line script
        run: echo Hello ${{ inputs.username }}

      - name: Print the environment variable
        run: echo "ENV var $USERNAME"

      - name: Show Current Date
        run: date

  checkout-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display files in the repository
        run: ls -la
