name: Hello GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Show System Information
        run: |
          echo "Running on $(uname -s) $(uname -r)"
          echo "Current user: $(whoami)"
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"

      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions!"

      - name: Show Current Date and Time
        run: date

  checkout-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display files in the repository
        run: ls -la

      - name: Show Git Status
        run: git status
