name: Hello GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Show System Information
        run: uname -a

      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions!"

      - name: Show Current Date and Time
        run: date
